image: node:latest

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - backend/node_modules/
    
stages:
  - merge-check
  - build
  - lint
  - release

allowed-to-merge:
  stage: merge-check
  only:
    - merge_requests
  script:
    - if [ "${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}" == "main" ] && [ "${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}" != "develop" ]; then
        echo "Cannot merge to the main branch directly. Please create a merge request from the develop branch.";
        exit 1;
      else
        exit 0;
      fi

build:
  stage: build
  only:
    refs:
      - merge_requests  
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
  script:
    - cd backend
    - npm install

lint:
  stage: lint
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - backend/node_modules/
  only:
    - merge_requests
  needs:
    - build
  script:
    - cd backend
    - npm run lint

release-backend:
  image: docker:cli
  stage: release
  services:
    - docker:dind
  only:
    - main
  before_script:
    - docker login -u "${DOCKER_REGISTRY_USER}" -p "${DOCKER_REGISTRY_PASSWORD}" ${DOCKER_REGISTRY}
  script:
    - docker build --pull --rm -f "./backend/Dockerfile" -t "zikria40/codidact-startup-coach-backend:latest" "./backend"
    - docker push "zikria40/codidact-startup-coach-backend:latest"