stages:
  - merge-check
  - build-and-publish

allowed-to-merge:
  image: ubuntu:latest
  stage: merge-check
  only:
    - merge_requests
  script:
    - if [ "${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}" == "main" ] && [ "${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}" != "develop" ]; then
        echo "Cannot merge to the main branch directly. Please create a merge request from the develop branch.";
        exit 1;
      else
        exit 0;
      fi

build-and-publish:
  image: docker:cli
  stage: build-and-publish
  services:
    - docker:dind
  only:
    - merge_requests
  before_script:
    - docker login -u "${DOCKER_REGISTRY_USER}" -p "${DOCKER_REGISTRY_PASSWORD}" ${DOCKER_REGISTRY}
  script:
    - docker build --pull --rm -f "./backend/Dockerfile" -t "zikria40/codidact-startup-coach-backend:latest" "./backend"
    - docker push "zikria40/codidact-startup-coach-backend:latest"